# -*- coding: utf-8 -*-
"""exercicegit1710.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bOR8Ggt44oC4m_RPc6xGshlbLzkQXLaa
"""

def ask_question(nb_attempts_left, question_sentence, right_answer): # three arguments
    if nb_attempts_left > 0:
        answer = input(question_sentence)
        answer = answer.lower()
        while answer != right_answer:
            nb_attempts_left -=1
            print("Sorry, you have {} chances left".format(nb_attempts_left))
            if nb_attempts_left == 0:
                print("Oh no, you lost the quiz...")
                break
            answer = input(question_sentence)
            answer = answer.lower()
    print('')
    return nb_attempts_left

questions_answers_list = [
    ("How many times France soccer team won the World Cup?", "2"),
    ("When Apple was founded?", "1976"),
    ("Who founded SpaceX?", "elon musk")
]

nb_attempts = 3

for question, answer in questions_answers_list :
    nb_attempts = ask_question(nb_attempts, question, answer) # calling the function

if nb_attempts > 0:
    print("Well done, you have win!")